export const products = [
  {
    id: 1,
    title: "Nueva York",
    price: 15000,
    stock: 4,
    shortDescription:
      "Nueva York, una ciudad llena de energía, cultura, historia y una oferta de entretenimiento incomparable.",
    pais: "Estados Unidos",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583688/EXPLORE/newYork_cpuknf.jpg",
  },
  {
    id: 2,
    title: "Venecia",
    price: 14500,
    stock: 5,
    shortDescription:
      "Una ciudad única y encantadora, construida sobre una red de canales en el mar Adriático. Un destino turístico romántico y pintoresco.",
    pais: "Italia",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583688/EXPLORE/venesia_rhm2vl.jpg",
  },
  {
    id: 3,
    title: "Madrid",
    price: 19000,
    stock: 5,
    shortDescription:
      "Una mezcla fascinante de historia, cultura y vibrante vida urbana. Madrid es un destino turístico emocionante y diverso.",
    pais: "España",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583688/EXPLORE/madrid_pmygpa.jpg",
  },
  {
    id: 4,
    title: "Barcelona",
    price: 17800,
    stock: 5,
    shortDescription:
      "Barcelona ofrece una vida cultural dinámica, con una animada escena artística, una deliciosa gastronomía y una animada vida nocturna.",
    pais: "España",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/barcelona_oajyx0.jpg",
  },
  {
    id: 5,
    title: "Singapur",
    price: 17800,
    stock: 5,
    shortDescription:
      "Además de su impresionante arquitectura moderna, ofrece una fusión única de culturas, exquisita cocina callejera, y una limpieza y eficiencia destacadas.",
    pais: "Singapur",
    category: "Asia",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/singapore_dxnouc.jpg",
  },
  {
    id: 6,
    title: "Estambul",
    price: 17800,
    stock: 5,
    shortDescription:
      "Una experiencia única al combinar la historia del Imperio Otomano con la modernidad. Sus mezquitas y cruceros lo hacen un destino cautivador.",
    pais: "Turquía",
    category: "Asia",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/istanbul_lguja3.jpg",
  },
  {
    id: 7,
    title: "Miami",
    price: 17800,
    stock: 5,
    shortDescription:
      "Playas de arena blanca, clima cálido y animada vida nocturna. Mezcla diversa de culturas con influencia latina notable y escena artística y gastronómica vibrante.",
    pais: "Estados Unidos",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/miami_qnk6mx.jpg",
  },
  {
    id: 8,
    title: "Londres",
    price: 17800,
    stock: 5,
    shortDescription:
      "Combina una rica historia, impresionantes monumentos y una emocionante escena cultural con museos de renombre y teatros de clase mundial.",
    pais: "Reino Unido",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/london_ckhu7l.jpg",
  },
  {
    id: 9,
    title: "Dubai",
    price: 17800,
    stock: 5,
    shortDescription:
      "La ciudad de los rascacielos. Ofrece una experiencia única por arquitectura futurista, centros comerciales y actividades en el desierto.",
    pais: "Dubai",
    category: "Asia",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583687/EXPLORE/dubai_dp9wmk.jpg",
  },
  {
    id: 10,
    title: "Tailandia",
    price: 17800,
    stock: 5,
    shortDescription:
      "Cautiva a los turistas con sus exóticos templos budistas, playas paradisíacas, una rica cultura tradicional y una deliciosa gastronomía.",
    pais: "Tailandia",
    category: "Asia",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/thailand_lkbynh.jpg",
  },
  {
    id: 11,
    title: "Tokio",
    price: 17800,
    stock: 5,
    shortDescription:
      "Combina la tradición con la tecnología de vanguardia. Experiencia única con su cultura pop, impresionantes rascacielos, templos históricos.",
    pais: "Japón",
    category: "Asia",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/tokio_g4d2f3.jpg",
  },
  {
    id: 12,
    title: "París",
    price: 17800,
    stock: 5,
    shortDescription:
      "Ciudad del amor y la luz, cautiva a los turistas con su icónica Torre Eiffel, hermosos bulevares, magníficos museos y su exquisita gastronomía.",
    pais: "Francia",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/paris_p6tmza.jpg",
  },
  {
    id: 13,
    title: "La Habana",
    price: 17800,
    stock: 5,
    shortDescription:
      "Un viaje en el tiempo con su encanto colonial, música contagiosa, autos clásicos y una vibrante escena cultural llena de ron y salsa.",
    pais: "Cuba",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/habana_jqyekf.jpg",
  },
  {
    id: 14,
    title: "Buenos Aires",
    price: 17800,
    stock: 5,
    shortDescription:
      "La ciudad del tango, cautiva con su arquitectura europea, animada vida nocturna, deliciosa comida y su espíritu artístico y cultural.",
    pais: "Argentina",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/buenos_aires_uohgjc.jpg",
  },
  {
    id: 15,
    title: "Río de Janeiro",
    price: 17800,
    stock: 5,
    shortDescription:
      "Icónicas playas, como Copacabana e Ipanema, el imponente Cristo Redentor, vibrantes desfiles de carnaval y una alegría contagiosa.",
    pais: "Brasil",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583686/EXPLORE/rioDeJaneiro_ofsmvj.jpg",
  },
  {
    id: 16,
    title: "Cancún",
    price: 17800,
    stock: 5,
    shortDescription:
      "Paraíso tropical con playas de arena blanca, aguas cristalinas del Caribe, emocionantes actividades acuáticas y una animada vida nocturna.",
    pais: "México",
    category: "América",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583685/EXPLORE/cancun_uo0ssp.jpg",
  },
  {
    id: 17,
    title: "Roma",
    price: 17800,
    stock: 5,
    shortDescription:
      "Deslumbra con su vasta historia, impresionante arquitectura antigua, como el Coliseo y el Vaticano, y su exquisita gastronomía italiana.",
    pais: "Italia",
    category: "Europa",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1685583685/EXPLORE/roma_x7iyff.jpg",
  },
  {
    id: 18,
    title: "Nueva Zelanda",
    price: 17800,
    stock: 3,
    shortDescription:
      "Montañas majestuosas y playas de ensueño. Ofrece aventuras al aire libre, cultura maorí y una hospitalidad cálida para los turistas.",
    pais: "Nueva Zelanda",
    category: "Oceanía",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1686709791/nuevaZelanda_gs3ezn.jpg",
  },
  {
    id: 19,
    title: "Sydney",
    price: 17800,
    stock: 0,
    shortDescription:
      "Combina sus monumentos con su animada escena cultural, playas de renombre y gran variedad gastronómica y de entretenimiento.",
    pais: "Australia",
    category: "Oceanía",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1686709791/sydney_hkk4fg.jpg",
  },
  {
    id: 20,
    title: "Bora Bora",
    price: 17800,
    stock: 5,
    shortDescription:
      "Un paraíso tropical de ensueño, conocido por sus exquisitas aguas turquesas, impresionantes bungalows sobre el agua y un ambiente romántico y relajado.",
    pais: "Polinesia Francesa",
    category: "Oceanía",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1686709792/boraBora_l894oo.jpg",
  },
  {
    id: 21,
    title: "Tahití",
    price: 17800,
    stock: 5,
    shortDescription:
      "Isla paradisíaca y exuberante, famosa por sus playas de arena blanca, aguas cristalinas, cultura polinesia vibrante y un ambiente tranquilo y romántico.",
    pais: "Polinesia Francesa",
    category: "Oceanía",
    img: "https://res.cloudinary.com/db8btnoov/image/upload/v1686709792/tahit%C3%AD_ohcdmr.jpg",
  },
];
